#!/usr/bin/env node
// Generate frontend/src/utils/themes.js from:
// - Built-in DaisyUI themes in node_modules/daisyui/theme
// - Custom themes declared in frontend/src/index.css via `@plugin 'daisyui/theme' { name: "..." }`

import fs from 'node:fs/promises'
import path from 'node:path'
import url from 'node:url'

const __dirname = path.dirname(url.fileURLToPath(import.meta.url))
const projectRoot = path.resolve(__dirname, '..')
const frontendRoot = projectRoot

const THEME_DIR = path.resolve(frontendRoot, 'node_modules', 'daisyui', 'theme')
const INDEX_CSS = path.resolve(frontendRoot, 'src', 'index.css')
const OUTPUT_FILE = path.resolve(frontendRoot, 'src', 'utils', 'themes.js')

async function readBuiltinThemes() {
  try {
    const entries = await fs.readdir(THEME_DIR, { withFileTypes: true })
    const names = new Set()
    for (const e of entries) {
      if (e.isDirectory()) {
        names.add(e.name)
      } else if (e.isFile() && e.name.endsWith('.css')) {
        names.add(path.basename(e.name, '.css'))
      }
    }
    return Array.from(names).sort()
  } catch (err) {
    // node_modules may not be installed yet; fallback to empty
    return []
  }
}

async function readCustomThemes() {
  try {
    const css = await fs.readFile(INDEX_CSS, 'utf8')
    const re = /@plugin\s+['"]daisyui\/theme['"]\s*\{[\s\S]*?name:\s*['"]([^'"\n]+)['"][\s\S]*?\}/g
    const found = new Set()
    for (const m of css.matchAll(re)) {
      if (m[1]) found.add(m[1])
    }
    return Array.from(found)
  } catch {
    return []
  }
}

function uniquePreserveOrder(list) {
  const seen = new Set()
  const out = []
  for (const item of list) {
    if (!item) continue
    if (seen.has(item)) continue
    seen.add(item)
    out.push(item)
  }
  return out
}

function buildFile(themes) {
  const body = `// This file is generated by scripts/generate-themes.mjs
// Do not edit manually.
const themes = ${JSON.stringify(themes, null, 2)};

export const light_theme = 'light';
export const dark_theme = 'dark';

export default themes;
`
  return body
}

async function main() {
  const builtin = await readBuiltinThemes()
  const custom = await readCustomThemes()
  const finalList = uniquePreserveOrder(['auto', ...builtin, ...custom])
  await fs.writeFile(OUTPUT_FILE, buildFile(finalList), 'utf8')
  console.log(`Wrote ${OUTPUT_FILE} with ${finalList.length} themes.`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})

