import { AtSign, FileCode2, FileUp, Layers, Users } from "lucide-react";

export const routes = [
  {
    key: "root",
    path: "/",
    fullPath: "/",
    area: "root",
  },
  {
    key: "login",
    path: "login",
    fullPath: "/login",
    area: "public",
  },
  {
    key: "createAccount",
    path: "create-account",
    fullPath: "/create-account",
    area: "public",
  },
  {
    key: "app",
    path: "app",
    fullPath: "/app",
    area: "layout",
  },
  {
    key: "users",
    path: "users",
    fullPath: "/app/users",
    area: "app",
    labelKey: "User",
    icon: Users,
    permissions: ["admin"],
    nav: true,
  },
  {
    key: "servers",
    path: "servers",
    fullPath: "/app/servers",
    area: "app",
    labelKey: "Server",
    icon: Layers,
    permissions: ["admin", "ops", "user"],
    nav: true,
  },
  {
    key: "serverId",
    path: ":serverId",
    area: "app-nested",
  },
  {
    key: "serverPorts",
    path: ":serverId/ports",
    area: "app-nested",
  },
  {
    key: "serverUsers",
    path: ":serverId/users",
    area: "app-nested",
  },
  {
    key: "files",
    path: "files",
    fullPath: "/app/files",
    area: "app",
    labelKey: "File Center",
    icon: FileUp,
    permissions: ["admin", "ops", "user"],
    nav: true,
  },
  {
    key: "contracts",
    path: "contracts",
    fullPath: "/app/contracts",
    area: "app",
    labelKey: "Schemas",
    icon: FileCode2,
    permissions: ["admin", "ops"],
    nav: true,
    end: true,
  },
  {
    key: "contractBuilder",
    path: "contracts/builder",
    fullPath: "/app/contracts/builder",
    area: "app",
  },
  {
    key: "contractBuilderById",
    path: "contracts/builder/:contractId",
    area: "app",
  },
  {
    key: "formRedirect",
    path: "form",
    fullPath: "/app/form",
    area: "app",
  },
  {
    key: "about",
    path: "about",
    fullPath: "/app/about",
    area: "app",
    labelKey: "About",
    icon: AtSign,
    permissions: ["admin", "ops", "user"],
    nav: true,
  },
  {
    key: "themes",
    path: "themes",
    fullPath: "/app/themes",
    area: "app",
  },
];
